services:
  - type: web
    name: astrology-fortune
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 60 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
